### ISSUE TITLE
Application displays nothing

### ISSUE THREAD

**Issue by sebastiaanfranken** [fsobolev/timeswitch#15]
When starting timeswitch it only displays a round blob with no UI, no window controls and nothing else.

![afbeelding](https://user-images.githubusercontent.com/608882/205521067-fa8ad03f-c480-4554-929c-6edadb866e25.png)

This happens on Fedora 37 Workstation and GNOME OS in a virtual machine.

**Comment by fsobolev** [comment]
~~Have you installed the app from flatpak? If so, please run in the terminal and check if there are any errors:
`flatpak run io.github.fsobolev.TimeSwitch`~~

**UPD**: I can reproduced it, will fix ASAP

**Comment by fsobolev** [comment]
Sorry for such a stupid bug 😅 I updated the app on Flathub, fixed version will be available within a few hours.
