### ISSUE TITLE
[Feature] Save last used Action settings

### ISSUE THREAD

**Issue by hyuri** [fsobolev/timeswitch#17]
Hi, great app!

It would be really handy if the app saved the last action settings I've selected. I often use the "Notification" action with "Sound" on, but, by default, "Power Off" is selected and "Sound" is off, so I have to set it up again every time.

**Comment by fsobolev** [comment]
Thanks for the suggestion! I implemented the feature, you can build and test it, or wait for the new release that I plan to upload on Flathub tomorrow ☺️

**Comment by hyuri** [comment]
So quick!😱 Awesome. Thank you!
