### ISSUE TITLE
[Feature] Keep playing notification sound until dismissed, like an alarm

### ISSUE THREAD

**Issue by hyuri** [fsobolev/timeswitch#18]
Hi!

Idea: Keep playing the notification sound, perhaps every second, until the notification is dismissed, like an alarm.

**Comment by fsobolev** [comment]
Like an alarm in GNOME Clocks?  Why not, I will implement it :)

**Comment by hyuri** [comment]
Yes, cool! :)

Maybe it could be an option as a checkbox under "Play sound", in case others prefer the sound play only once.

**Comment by fsobolev** [comment]
This feature has been implemented. A new release will be published when all translations will be updated.

**Comment by hyuri** [comment]
You're awesome. Thank you!
