### ISSUE TITLE
Translations on Weblate

### ISSUE THREAD

**Issue by fsobolev** [fsobolev/timeswitch#48]
Feb 4th will be 3 month since the first release of Time Switch, I will be able to setup a project on Weblate.

**Comment by fsobolev** [comment]
@DeltaVeintiuno @Vistaus @plasmus777 @eson57 @albanobattistella @sabriunal @gregorni @RoepLuke @sekalengrengginang @rene-coty 
Dear translators! Weblate project was created: https://hosted.weblate.org/engage/timeswitch/
Let me know if you still want me to ping you when changes in translations are required before new versions releases, otherwise I won't bother you with pings anymore.
I'm closing this issue but feel free to comment here if you find some issues with weblate configuration.

**Comment by ghost** [comment]
I'd still like to be pinged, but great that there's a Weblate now!

**Comment by eson57** [comment]
Weblate already pinging me. ;)
