### ISSUE TITLE
Make the app easy to use with only keyboard

### ISSUE THREAD

**Issue by fsobolev** [fsobolev/timeswitch#49]
I want to provide keyboard shortcuts to easily access most of UI elements in the app. Probably something like this:

- Ctrl+W - close window (if timer is running, this will only hide the window)
- Ctrl+Q - quit (if timer is running, a dialog will appear to confirm stopping the timer and quit)
- Ctrl+? - shortcuts dialog

**Setup**
- Alt+H, Alt+M, Alt+S - focus hours/minutes/seconds spin
- Alt+R - reset
- Ctrl+M - change mode
- Ctrl+Enter - start timer

**Actions**
- Ctrl+O - power off
- Ctrl+R - reboot
- Ctrl+S - suspend
- Ctrl+N - notification, text entry gets focused
- Ctrl+B - play sound
- Ctrl+U - until stopped
- Ctrl+C - commands

**Commands**
- Ctrl+1..0 - select command 1..10
- Ctrl+A - add command
- Ctrl+D - remove selected command
- Ctrl+Backspace, Esc - back

**Running**
- Ctrl+P - toggle pause
- Ctrl+S - stop

About button will be replaced with menu button, the menu will contain "Keyboard shortcuts", "About" and "Quit" (same as Ctrl+Q shortcut).

**Comment by ghost** [comment]
Do you think `Esc` might be better for back option? Also, some of the options don't need `Ctrl`, I'd say, for instance Pause or Stop.

**Comment by ghost** [comment]
Btw, you entered the same shortcut for Minutes and Mode.

**Comment by fsobolev** [comment]
> Btw, you entered the same shortcut for Minutes and Mode.

Oh, right, something different is needed for Mode.

> Do you think Esc might be better for back option?

It doesn't follow the pattern of other shortcuts, but I think it will be fine to have both Ctrl+Backspace and Esc for this option.

> Also, some of the options don't need Ctrl, I'd say, for instance Pause or Stop.

I will try to use just "P" and "S", I'm not sure it will work well, I don't know if these shortcuts will be triggered when a user type these letters in entries.

**Comment by ghost** [comment]
> I will try to use just "P" and "S", I'm not sure it will work well, I don't know if these shortcuts will be triggered when a user type these letters in entries.

True, I hadn't thought about that. I guess we'll have to see about that.

> Oh, right, something different is needed for Mode.

How about Mod`E`? ;P

**Comment by ghost** [comment]
Also, `Esc` to pause the timer would be nice, I think.

**Comment by fsobolev** [comment]
> How about Mod`E`? ;P

Or keep Ctrl+M for Mode, but use Alt+H/M/S for spins, and also Alt+R for Reset.

**Comment by ghost** [comment]
That's a good idea! That way, all the options of the upper input field are `Alt`, which is kind of cool.

**Comment by ghost** [comment]
How about `Ctrl + Enter` to start the timer?

**Comment by ghost** [comment]
There's also `Space` to pause... @fsobolev What do you think?
