### ISSUE TITLE
You could use dbus-python instead of os.system for dbuss class

### ISSUE THREAD

**Issue by mijorus** [fsobolev/timeswitch#50]
https://github.com/fsobolev/timeswitch/blob/2764ee5e942c375f495ba370c7a75ef1714293a6/src/actions.py#L54

Like this
https://github.com/mijorus/smile/blob/2735e9f129eecc78f14bda7827c72794d82c2ee8/src/Settings.py#L213

This is not a bug, I am just pointing it out

**Comment by fsobolev** [comment]
Thank you! I will try it :)
