### ISSUE TITLE
[Feature] Ability to Save & Load Presets

### ISSUE THREAD

**Issue by hyuri** [fsobolev/timeswitch#56]
Hi again!

First of all, I just want to say thank you for making such an excellent app! Great job! I've been using it everyday.

Now, I just had an idea:
What do you think of adding a presets option? That way we can save timers we use often, making it even quicker to use the app.
I usually use the same settings for different timers throughout the day. Cooking, for example, certain recipes take the same amount time to cook, so being able to save a preset for "beans", "rice", etc. would make save some time.

Be able to create and add them to categories — like "Recipes", "Maintenance", etc. — would make it even nicer.

Example:

![Time Switch Presets Concept](https://user-images.githubusercontent.com/18584014/219047577-f604a414-36b0-494c-8814-c1c393db4c5d.png)

**Comment by fsobolev** [comment]
I think categories will add unnecessary complexity. I don't expect somebody to have dozens of presets, but maybe 5-10, and for this amount I don't think categories are needed. But overall, great idea, thanks!

**Comment by hyuri** [comment]
> I think categories will add unnecessary complexity. I don't expect somebody to have dozens of presets, but maybe 5-10, and for this amount I don't think categories are needed. But overall, great idea, thanks!

👌 I see myself mounting dozens of presets over the years, but maybe it's just me😂 It's definitely non-essential, so if it adds complexity, forget about it!

**Comment by fsobolev** [comment]
Sorry that you have to wait for this feature so long. It is now implemented, I'm going to wait for translations update and GNOME 44 Platform release (~ March 22nd) and then I will publish a new version.

|Preset creation|Presets submenu|Managing presets|
| --- | --- | --- |
| ![](https://user-images.githubusercontent.com/117388856/226176599-012c4955-eb00-4ab0-8f2d-a3b00b626013.png) | ![](https://user-images.githubusercontent.com/117388856/226176600-58a79434-0f35-457c-be7b-0cba8bd93336.png) | ![](https://user-images.githubusercontent.com/117388856/226176602-99373b48-3dd8-4488-9206-ed3b86159696.png) |

Each preset remembers and restores timer mode, timer value, action and its parameters (including notification text for notification action).

**Comment by hyuri** [comment]
Awesome!! It didn't take very long. Thank you very much! Your great work on this app is really appreciated.
